name: Component Tests
on: [push]

jobs:
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.7.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-store
        shell: bash
        run: |
          echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      # Run linting first - will block subsequent steps if it fails
      - name: Run linting
        id: lint
        run: pnpm lint

      # Only run component tests if linting passes
      - name: Run component tests
        id: component-tests
        run: pnpm test:component
        env:
          CI: true
          
      # Trigger Netlify build only if both linting and component tests pass
      # The if: success() condition ensures all previous steps must have succeeded
      - name: Trigger Netlify build
        if: success()
        run: |
          curl -X POST -d {} "${{ secrets.NETLIFY_BUILD_HOOK_URL }}"
